---
title: "World Map"
author: "M. Salmon"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{World Map}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

In this vignette I want to plot a map of the world with points to represent monitors whose data is available on the platform. However there are not geographical coordinates for all locations so the map will not be exhaustive.

Loading packages.

```{r, warning=FALSE, message=FALSE}
library("OpenStreetMap")
library("ggplot2")
library("Ropenaq")
```

Getting coordinates and transformating it.

```{r, warning=FALSE, message=FALSE, eval=FALSE}
lat <- NULL
long <- NULL
name <- NULL

for (country in Ropenaq::countries()$code){
  locationsCountry <- Ropenaq::locations(country=country)
  lat <- c(lat, locationsCountry$latitude)
  long <- c(long, locationsCountry$longitude)
  name <- c(name, locationsCountry$location)
}

dataGeo <- data.frame(latitude=lat,
                      longitude=long,
                            name=name)
dataGeo <- dataGeo[!is.na(dataGeo$latitude),]
monitors_merc <- as.data.frame(
  projectMercator(dataGeo$latitude, dataGeo$longitude, drop=FALSE))
monitors_merc$name <- dataGeo$name
```

Getting the empty map.

```{r fig.width=7, fig.height=4, cache=TRUE, eval=FALSE}

worldMap <- OpenStreetMap::openmap(c(85,-179.99999),
                                    c(-60,179.99999),
               type="stamen-watercolor")
ggplot2::autoplot(worldMap)+ theme_bw()
```

Map with monitors.

```{r fig.width=7, fig.height=4, eval=FALSE}
ggplot2::autoplot(worldMap)+ theme_bw()+
  geom_point(data = monitors_merc, aes(x=x, y=y), size=2, shape=7)+
  theme(axis.line=element_blank(),axis.text.x=element_blank(),
       axis.text.y=element_blank(),axis.ticks=element_blank(),
       axis.title.x=element_blank(),
       axis.title.y=element_blank(),legend.position="none",
       panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),
       panel.grid.minor=element_blank(),plot.background=element_blank())+
   ggtitle("OpenAQ data sources with geographical coordinates") +
  theme(plot.title = element_text(lineheight=1, face="bold"))

```
